// frontend/src/components/board/KanbanColumn.vue
<template>
  <div class="kanban-column">
    <div class="column-header">
      <div class="column-title">
        <span class="dot" :class="status" />
        <span>{{ labels[status] }}</span>
        <span class="count">{{ tasks.length }}</span>
      </div>
    </div>
    <div class="column-body">
      <TaskCard
        v-for="task in tasks"
        :key="task.id"
        :task="task"
        @click="$emit('openTask', task.id)"
      />
      <div v-if="tasks.length === 0" class="empty-col">暂无任务</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Task, TaskStatus } from '@/types'
import TaskCard from './TaskCard.vue'

defineProps<{ status: TaskStatus; tasks: Task[] }>()
defineEmits<{ openTask: [id: string] }>()

const labels: Record<TaskStatus, string> = {
  todo: '待处理', in_progress: '进行中', done: '已完成', blocked: '已阻塞'
}
</script>

<style scoped>
.kanban-column { display: flex; flex-direction: column; min-width: 260px; flex: 1; }
.column-header { padding: 0 0 12px 0; }
.column-title { display: flex; align-items: center; gap: 6px; font-size: 13px; font-weight: 700; color: var(--color-foreground); }
.dot { width: 8px; height: 8px; border-radius: 50%; }
.dot.todo { background: #94a3b8; }
.dot.in_progress { background: #f59e0b; }
.dot.done { background: #059669; }
.dot.blocked { background: #dc2626; }
.count { background: var(--color-muted); color: var(--color-text-muted); font-size: 11px; padding: 1px 6px; border-radius: 999px; }
.column-body { display: flex; flex-direction: column; gap: 8px; min-height: 120px; }
.empty-col { font-size: 12px; color: var(--color-text-subtle); text-align: center; padding: 20px 0; }
</style>

// frontend/src/components/tasks/KanbanColumn.tsx
import { SortableContext, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { TaskCard } from './TaskCard'
import type { Task, TaskStatus } from '@/api/types'

interface KanbanColumnProps {
  status: TaskStatus
  tasks: Task[]
}

const statusConfig: Record<TaskStatus, { label: string; dotColor: string }> = {
  todo:        { label: '待办',   dotColor: '#92400e' },
  in_progress: { label: '进行中', dotColor: '#2563eb' },
  done:        { label: '已完成', dotColor: '#16a34a' },
  blocked:     { label: '阻塞',   dotColor: '#dc2626' },
}

export function KanbanColumn({ status, tasks }: KanbanColumnProps) {
  const cfg = statusConfig[status]

  return (
    <div className="min-w-[240px] flex-1 bg-[#f7f7f5] rounded-lg p-3 flex flex-col">
      <div className="flex items-center gap-2 mb-3">
        <span
          className="w-2.5 h-2.5 rounded-full flex-shrink-0"
          style={{ backgroundColor: cfg.dotColor }}
        />
        <span className="text-sm font-semibold text-[#191919]">{cfg.label}</span>
        <span className="ml-auto text-[11px] font-semibold bg-[#e8e8e6] text-[#555] rounded-full px-2 py-0.5">
          {tasks.length}
        </span>
      </div>

      <SortableContext items={tasks.map((t) => t.id)} strategy={verticalListSortingStrategy}>
        <div className="flex flex-col gap-2 flex-1">
          {tasks.length === 0 ? (
            <div className="flex items-center justify-center py-8 text-sm text-[#aaa]">
              暂无任务
            </div>
          ) : (
            tasks.map((task) => <TaskCard key={task.id} task={task} />)
          )}
        </div>
      </SortableContext>
    </div>
  )
}
