// frontend/src/components/board/TaskDrawer.vue
<template>
  <div class="drawer-overlay" @click.self="$emit('close')">
    <div class="drawer" v-if="task">
      <!-- 头部 -->
      <div class="drawer-header">
        <h3 class="drawer-title">{{ task.title }}</h3>
        <button class="btn-ghost close-btn" @click="$emit('close')">
          <X :size="18" />
        </button>
      </div>

      <!-- 元信息 -->
      <div class="drawer-meta">
        <div class="meta-row">
          <span class="meta-label">状态</span>
          <select v-model="localStatus" class="meta-select" :disabled="!canEdit">
            <option value="todo">待处理</option>
            <option value="in_progress">进行中</option>
            <option value="done">已完成</option>
            <option value="blocked">已阻塞</option>
          </select>
        </div>
        <div class="meta-row">
          <span class="meta-label">优先级</span>
          <PriorityBadge :priority="task.priority" />
        </div>
        <div class="meta-row">
          <span class="meta-label">负责人</span>
          <span class="meta-value">{{ task.assignee?.name || '未分配' }}</span>
        </div>
        <div v-if="task.due_date" class="meta-row">
          <span class="meta-label">截止日期</span>
          <span class="meta-value">{{ task.due_date }}</span>
        </div>
      </div>

      <!-- 进度 -->
      <div class="drawer-section">
        <div class="section-label">完成进度</div>
        <ProgressSlider v-model="localProgress" />
      </div>

      <!-- 进展记录输入 -->
      <div v-if="canEdit" class="drawer-section">
        <div class="section-label">记录今日进展</div>
        <textarea
          v-model="logContent"
          class="log-input"
          placeholder="描述今天完成了什么…"
          rows="3"
        />
        <button
          class="btn-primary submit-btn"
          :disabled="!logContent.trim() || submitting"
          @click="handleSubmit"
        >
          {{ submitting ? '提交中…' : '提交进展' }}
        </button>
      </div>

      <!-- 历史日志 -->
      <div class="drawer-section">
        <div class="section-label">进展历史</div>
        <div v-if="logs.length === 0" class="no-logs">暂无进展记录</div>
        <div v-for="log in logs" :key="log.id" class="log-item">
          <div class="log-meta">
            <span class="log-user">{{ log.user.name }}</span>
            <span class="log-time">{{ formatTime(log.created_at) }}</span>
            <span class="log-progress">{{ log.progress }}%</span>
          </div>
          <p class="log-content">{{ log.content }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { X } from 'lucide-vue-next'
import type { Task, TaskLog, TaskStatus } from '@/types'
import { useAuthStore } from '@/stores/auth'
import PriorityBadge from '@/components/common/PriorityBadge.vue'
import ProgressSlider from '@/components/common/ProgressSlider.vue'

const props = defineProps<{ task: Task | null; logs: TaskLog[] }>()
const emit = defineEmits<{
  close: []
  submitLog: [payload: { content: string; progress: number; status: string }]
}>()

const auth = useAuthStore()
const canEdit = ref(auth.isAdmin || props.task?.assignee?.id === auth.user?.id)

const localStatus = ref<TaskStatus>(props.task?.status ?? 'todo')
const localProgress = ref(props.task?.progress ?? 0)
const logContent = ref('')
const submitting = ref(false)

watch(() => props.task, (t) => {
  if (t) {
    localStatus.value = t.status
    localProgress.value = t.progress
    canEdit.value = auth.isAdmin || t.assignee?.id === auth.user?.id
  }
}, { immediate: true })

async function handleSubmit() {
  if (!logContent.value.trim()) return
  submitting.value = true
  try {
    emit('submitLog', {
      content: logContent.value,
      progress: localProgress.value,
      status: localStatus.value,
    })
    logContent.value = ''
  } finally {
    submitting.value = false
  }
}

function formatTime(iso: string) {
  const d = new Date(iso)
  return d.toLocaleString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}
</script>

<style scoped>
.drawer-overlay {
  position: fixed; inset: 0; z-index: 50;
  background: rgba(15,23,42,0.3);
  display: flex; justify-content: flex-end;
}
.drawer {
  width: 400px; height: 100%; background: white;
  overflow-y: auto; padding: 20px;
  box-shadow: var(--shadow-lg);
  animation: slideIn 200ms ease-out;
}
@keyframes slideIn {
  from { transform: translateX(100%); }
  to { transform: translateX(0); }
}
.drawer-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 16px; }
.drawer-title { font-size: 16px; font-weight: 700; color: var(--color-foreground); line-height: 1.4; flex: 1; }
.close-btn { color: var(--color-text-subtle); flex-shrink: 0; }

.drawer-meta { display: flex; flex-direction: column; gap: 10px; margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid var(--color-border); }
.meta-row { display: flex; align-items: center; gap: 10px; }
.meta-label { font-size: 12px; color: var(--color-text-subtle); width: 56px; flex-shrink: 0; }
.meta-value { font-size: 13px; color: var(--color-foreground); }
.meta-select { font-size: 12px; border: 1px solid var(--color-border); border-radius: var(--radius-sm); padding: 3px 8px; background: white; }

.drawer-section { margin-bottom: 20px; }
.section-label { font-size: 12px; font-weight: 700; color: var(--color-text-subtle); text-transform: uppercase; letter-spacing: 0.4px; margin-bottom: 10px; }

.log-input {
  width: 100%; border: 1px solid var(--color-border); border-radius: var(--radius-md);
  padding: 10px 12px; font-size: 13px; resize: vertical;
  transition: border-color var(--transition-fast);
}
.log-input:focus { border-color: var(--color-primary); }
.submit-btn { margin-top: 8px; width: 100%; }
.submit-btn:disabled { opacity: 0.5; cursor: not-allowed; }

.no-logs { font-size: 13px; color: var(--color-text-subtle); text-align: center; padding: 16px 0; }
.log-item { padding: 10px 0; border-bottom: 1px solid var(--color-border); }
.log-item:last-child { border-bottom: none; }
.log-meta { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }
.log-user { font-size: 12px; font-weight: 600; color: var(--color-foreground); }
.log-time { font-size: 11px; color: var(--color-text-subtle); flex: 1; }
.log-progress { font-size: 11px; font-weight: 600; color: var(--color-primary); }
.log-content { font-size: 13px; color: var(--color-text-muted); line-height: 1.5; }
</style>

// frontend/src/components/tasks/TaskDrawer.tsx
import React from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { X } from 'lucide-react'
import { toast } from 'sonner'
import { tasksApi } from '@/api/tasks'
import { Button } from '@/components/ui/button'
import { PriorityBadge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { useUIStore } from '@/store/uiStore'
import { formatDate, formatDateTime } from '@/lib/utils'
import type { Task, TaskStatus } from '@/api/types'

interface TaskDrawerProps {
  taskId: string
  projectId: string
  tasks: Task[]
}

const STATUS_OPTIONS: { value: TaskStatus; label: string }[] = [
  { value: 'todo', label: '待办' },
  { value: 'in_progress', label: '进行中' },
  { value: 'done', label: '已完成' },
  { value: 'blocked', label: '阻塞' },
]

export function TaskDrawer({ taskId, projectId, tasks }: TaskDrawerProps) {
  const closeDrawer = useUIStore((s) => s.closeDrawer)
  const queryClient = useQueryClient()

  const task = tasks.find((t) => t.id === taskId)

  const [logContent, setLogContent] = React.useState('')
  const [progress, setProgress] = React.useState(task?.progress ?? 0)
  const [status, setStatus] = React.useState<TaskStatus>(task?.status ?? 'todo')

  React.useEffect(() => {
    if (task) {
      setProgress(task.progress)
      setStatus(task.status)
    }
  }, [task])

  const { data: logs, isLoading: logsLoading } = useQuery({
    queryKey: ['logs', taskId],
    queryFn: () => tasksApi.getLogs(taskId).then((r) => r.data),
    enabled: !!taskId,
  })

  const addLogMutation = useMutation({
    mutationFn: () =>
      tasksApi.addLog(taskId, { content: logContent, progress, status }),
    onSuccess: () => {
      toast.success('进展已记录')
      setLogContent('')
      queryClient.invalidateQueries({ queryKey: ['logs', taskId] })
      queryClient.invalidateQueries({ queryKey: ['tasks', projectId] })
    },
    onError: () => {
      toast.error('提交失败，请重试')
    },
  })

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!logContent.trim()) return
    addLogMutation.mutate()
  }

  if (!task) return null

  const sortedLogs = logs ? [...logs].sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  ) : []

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/30 z-40"
        onClick={closeDrawer}
      />

      {/* Drawer */}
      <div className="fixed right-0 top-0 h-full w-[480px] bg-white shadow-lg z-50 flex flex-col animate-slide-in-right">
        {/* Header */}
        <div className="flex items-start justify-between gap-3 px-6 py-4 border-b border-[#e8e8e6]">
          <h2 className="text-base font-semibold text-[#191919] leading-snug flex-1">
            {task.title}
          </h2>
          <button
            onClick={closeDrawer}
            className="flex-shrink-0 w-7 h-7 flex items-center justify-center rounded-md hover:bg-[#f0f0ee] text-[#555] transition-colors"
          >
            <X size={16} />
          </button>
        </div>

        {/* Scrollable content */}
        <div className="flex-1 overflow-y-auto scrollbar-thin px-6 py-4 space-y-5">
          {/* Meta */}
          <div className="flex flex-wrap gap-3 text-sm">
            <div className="flex items-center gap-1.5">
              <span className="text-[#8c8c8c] text-xs">状态</span>
              <select
                value={status}
                onChange={(e) => setStatus(e.target.value as TaskStatus)}
                className="text-xs border border-[#e8e8e6] rounded-md px-2 py-1 bg-white text-[#191919] outline-none focus:ring-1 focus:ring-blue-400"
              >
                {STATUS_OPTIONS.map((opt) => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-[#8c8c8c] text-xs">优先级</span>
              <PriorityBadge priority={task.priority} />
            </div>
            {task.assignee && (
              <div className="flex items-center gap-1.5">
                <span className="text-[#8c8c8c] text-xs">负责人</span>
                <div className="flex items-center gap-1">
                  <div className="w-5 h-5 rounded-full bg-[#e8e8e6] flex items-center justify-center text-[10px] font-semibold text-[#555]">
                    {task.assignee.name.charAt(0).toUpperCase()}
                  </div>
                  <span className="text-xs text-[#191919]">{task.assignee.name}</span>
                </div>
              </div>
            )}
            {task.due_date && (
              <div className="flex items-center gap-1.5">
                <span className="text-[#8c8c8c] text-xs">截止日</span>
                <span className="text-xs text-[#191919]">{formatDate(task.due_date)}</span>
              </div>
            )}
          </div>

          {/* Progress */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-xs font-medium text-[#555]">进度</span>
              <span className="text-xs font-semibold text-[#191919]">{progress}%</span>
            </div>
            <input
              type="range"
              min={0}
              max={100}
              value={progress}
              onChange={(e) => setProgress(Number(e.target.value))}
              className="w-full h-1.5 accent-blue-500 cursor-pointer"
            />
          </div>

          {/* Log entry form */}
          <form onSubmit={handleSubmit} className="space-y-2">
            <p className="text-xs font-medium text-[#555]">记录进展</p>
            <textarea
              value={logContent}
              onChange={(e) => setLogContent(e.target.value)}
              placeholder="记录今日进展…"
              rows={3}
              className="w-full text-sm border border-[#e8e8e6] rounded-md px-3 py-2 outline-none focus:ring-1 focus:ring-blue-400 resize-none text-[#191919] placeholder:text-[#bbb]"
            />
            <div className="flex justify-end">
              <Button
                type="submit"
                disabled={!logContent.trim() || addLogMutation.isPending}
                className="text-xs h-8 px-4"
              >
                {addLogMutation.isPending ? '提交中…' : '提交进展'}
              </Button>
            </div>
          </form>

          {/* Log history */}
          <div>
            <p className="text-xs font-medium text-[#555] mb-2">进展历史</p>
            {logsLoading ? (
              <div className="space-y-3">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="space-y-1.5">
                    <Skeleton className="h-3 w-32" />
                    <Skeleton className="h-10 w-full" />
                  </div>
                ))}
              </div>
            ) : sortedLogs.length === 0 ? (
              <p className="text-xs text-[#aaa] py-4 text-center">暂无进展记录</p>
            ) : (
              <div className="space-y-3">
                {sortedLogs.map((log) => (
                  <div key={log.id} className="border border-[#e8e8e6] rounded-md p-3 bg-[#fafafa]">
                    <div className="flex items-center justify-between mb-1.5">
                      <div className="flex items-center gap-2">
                        <div className="w-5 h-5 rounded-full bg-[#e8e8e6] flex items-center justify-center text-[10px] font-semibold text-[#555]">
                          {log.user.name.charAt(0).toUpperCase()}
                        </div>
                        <span className="text-xs font-medium text-[#191919]">{log.user.name}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] text-[#8c8c8c] font-medium">{log.progress}%</span>
                        <span className="text-[10px] text-[#aaa]">{formatDateTime(log.created_at)}</span>
                      </div>
                    </div>
                    <p className="text-xs text-[#555] leading-relaxed">{log.content}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  )
}
