// frontend/src/components/tasks/TaskCard.tsx
import React from 'react'
import { useSortable } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { PriorityBadge } from '@/components/ui/badge'
import { useUIStore } from '@/store/uiStore'
import { formatDate } from '@/lib/utils'
import type { Task } from '@/api/types'

interface TaskCardProps {
  task: Task
}

export function TaskCard({ task }: TaskCardProps) {
  const openDrawer = useUIStore((s) => s.openDrawer)
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: task.id,
  })

  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0 : 1,
  }

  const isOverdue = task.due_date ? new Date(task.due_date) < new Date() && task.status !== 'done' : false

  return (
    <div
      ref={setNodeRef}
      style={style}
      {...attributes}
      {...listeners}
      onClick={() => openDrawer(task.id)}
      className="bg-white border border-[#e8e8e6] rounded-md p-3 cursor-pointer hover:shadow-md hover:-translate-y-0.5 transition-all select-none"
    >
      <div className="flex items-start justify-between gap-2 mb-2">
        <p className="font-semibold text-sm text-[#191919] leading-snug flex-1">{task.title}</p>
        {task.assignee && (
          <div className="flex-shrink-0 w-6 h-6 rounded-full bg-[#e8e8e6] flex items-center justify-center text-[11px] font-semibold text-[#555]">
            {task.assignee.name.charAt(0).toUpperCase()}
          </div>
        )}
      </div>

      <div className="flex items-center gap-1.5 mb-2">
        <PriorityBadge priority={task.priority} />
      </div>

      {task.progress > 0 && (
        <div className="mb-2">
          <div className="h-[3px] w-full bg-[#e8e8e6] rounded-full overflow-hidden">
            <div
              className="h-full bg-blue-500 rounded-full"
              style={{ width: `${task.progress}%` }}
            />
          </div>
        </div>
      )}

      {task.due_date && (
        <p className={`text-[11px] ${isOverdue ? 'text-red-500' : 'text-[#8c8c8c]'}`}>
          {formatDate(task.due_date)}
        </p>
      )}
    </div>
  )
}

// frontend/src/components/board/TaskCard.vue
<template>
  <div class="task-card" @click="$emit('click')">
    <div class="card-top">
      <span class="task-title">{{ task.title }}</span>
      <PriorityBadge :priority="task.priority" />
    </div>
    <div class="card-meta">
      <StatusBadge :status="task.status" />
      <div v-if="task.assignee" class="assignee">
        <span class="avatar">{{ task.assignee.name[0] }}</span>
        <span>{{ task.assignee.name }}</span>
      </div>
    </div>
    <div v-if="task.progress > 0" class="progress-bar">
      <div class="progress-fill" :style="{ width: task.progress + '%' }" />
    </div>
    <div v-if="task.due_date" class="due-date" :class="{ overdue: isOverdue }">
      {{ task.due_date }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Task } from '@/types'
import StatusBadge from '@/components/common/StatusBadge.vue'
import PriorityBadge from '@/components/common/PriorityBadge.vue'

const props = defineProps<{ task: Task }>()
defineEmits<{ click: [] }>()

const isOverdue = computed(() =>
  props.task.due_date ? new Date(props.task.due_date) < new Date() : false
)
</script>

<style scoped>
.task-card {
  background: white; border: 1px solid var(--color-border);
  border-radius: var(--radius-md); padding: 12px;
  cursor: pointer; transition: all var(--transition-fast);
  box-shadow: var(--shadow-sm);
}
.task-card:hover { box-shadow: var(--shadow-md); border-color: #bfdbfe; transform: translateY(-1px); }
.card-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; margin-bottom: 8px; }
.task-title { font-size: 13px; font-weight: 600; color: var(--color-foreground); line-height: 1.4; }
.card-meta { display: flex; align-items: center; justify-content: space-between; }
.assignee { display: flex; align-items: center; gap: 4px; font-size: 11px; color: var(--color-text-muted); }
.avatar {
  width: 20px; height: 20px; border-radius: 50%;
  background: var(--color-primary); color: white;
  font-size: 10px; font-weight: 700;
  display: flex; align-items: center; justify-content: center;
}
.progress-bar { height: 4px; background: var(--color-border); border-radius: 2px; margin-top: 8px; overflow: hidden; }
.progress-fill { height: 4px; background: var(--color-primary); border-radius: 2px; transition: width 200ms; }
.due-date { font-size: 11px; color: var(--color-text-subtle); margin-top: 6px; }
.due-date.overdue { color: var(--color-destructive); }
</style>
